global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yaml"

scrape_configs:
  - job_name: "pdf-sku-server"
    metrics_path: /api/v1/metrics
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ["pdf-sku"]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: pdf-sku-server
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: postgresql

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: redis
