apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pdf-sku
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - server-deployment.yaml
  - server-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
