apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pdf-sku
bases:
  - ../../base
patchesStrategicMerge:
  - server-patch.yaml
replicas:
  - name: pdf-sku-server
    count: 3
  - name: pdf-sku-web
    count: 2
